### ISSUE TITLE
path update does not work if similar paths found

### ISSUE THREAD

**Issue by thezoggy** [Notifiarr/toolbarr#100]
tried to use this to migrate sonarr v4 db from windows to linux
![Toolbarr_2023-07-24_17-19-39](http://zoggy.net/Toolbarr_2023-07-24_18-01-00.png)

If I change `S:\TV` to `/tv/`  then it wrongly changes ALL the paths rather than just the expected 350

even though it says:
![Toolbarr_2023-07-24_17-21-45](https://github.com/Notifiarr/toolbarr/assets/500882/40c39b18-e1c6-4263-ba67-9a556fca6370)

which results in broken paths:
![DB_Browser_for_SQLite_2023-07-24_17-22-35](https://github.com/Notifiarr/toolbarr/assets/500882/6b5bf2d7-09b8-4745-8899-3d6d2a341d26)

**Comment by thezoggy** [comment]
and trying to just start from bottom of list to use `S:\TV-UHD` since it wouldnt match any of the above..  looks like that worked per looking at the db. 



![Toolbarr_2023-07-24_18-05-39](https://github.com/Notifiarr/toolbarr/assets/500882/5f38a002-0043-4d5b-972e-6f7e20a16e77)


gui has wrong totals for `S:\TV` as theres 350 total, but only 288 
```
select count(*) from series where Path like 'S:\TV\%'
288
```

so what will prob happen if I was to keep converting these from bottom up, the ending result should just be what is actually just `S:\TV`

**Comment by davidnewhall** [comment]
Thanks for the feedback! I will improve this. :)

**Comment by davidnewhall** [comment]
A possible fix for this is available on the unstable download page. Please try it out and let me know if it works any better. Happy to keep fixing bugs if you find them. Thank you! 

https://unstable.golift.io/toolbarr

**Comment by thezoggy** [comment]
grabbed latest dev, tested and looks like it works now:
![Toolbarr_2023-08-19_19-40-04](https://github.com/Notifiarr/toolbarr/assets/500882/d6cdb6b2-ef96-419a-bb24-3fb5660b37ac)

and confirmed db paths look correct
![DB_Browser_for_SQLite_2023-08-19_19-41-26](https://github.com/Notifiarr/toolbarr/assets/500882/001633c3-54f2-46b7-af7d-701980710f03)

**Comment by davidnewhall** [comment]
Woo! 

I'd appreciate any other feedback you may have. Design, layout, look, feel, other features. 

Thank you for the bug report and testing the fix!
