### ISSUE TITLE
[FEAT] - Starr bulk profile, custom formats, quality profiles,  indexer, blocklist, list exclusion, & list edit

### ISSUE THREAD

**Issue by bakerboy448** [Notifiarr/toolbarr#11]
- [x] Indexers
- [x] Import lists
- [x] Import list exclusions
- [x] Quality profiles
- [x] Block list
- [x] Download Clients

**Comment by davidnewhall** [comment]
Sounds interesting. Please add a workflow example and/or problem statement in the description.

**Comment by bakerboy448** [comment]
all can be done via the api but not in bulk and requires looping

Lists
- can only edit 1x1
- Can't bulk delete
- Can't bulk edit root folders

indexers
- can't bulk delete
- Can't bulk edit (rss/interactive/auto)

Quality profiles
- can't bulk delete

blocklist
- can't bulk delete

**Comment by davidnewhall** [comment]
I think I have all of these in starr now. Anything we need/want for Prowlarr specifically?

**Comment by davidnewhall** [comment]
Everything except block lists is finished. Please check it out and provide feedback.
