### ISSUE TITLE
import/export settings

### ISSUE THREAD

**Issue by medwards180** [Notifiarr/toolbarr#131]
I've on occasion wanted to or needed to wipe out my db in one of the arr applications and start over.  Restarting requires screenshots of configurations and settings for indexers, downloaders, media management, etc.   it would be helpful if toolbarr could export all settings from one of the arr applications and inport those settings back after the db has been reset.  A nice to have would be to have the ability to import the settings into a different arr application.  Example: if i set up a bunch of jackett indexers in sonarr, i would export the settings and then import the file into radarr, lidarr, etc.

**Comment by austinwbest** [comment]
I would highly recommend if that is what you do, you drop Jackett and swap to Prowlarr since it automatically pushes indexers to the starr apps and keeps them in sync.

Just a thought for the indexer management.

**Comment by davidnewhall** [comment]
Seems like a reasonable idea. Tell me exactly which settings you need. I have these from your original post:
- indexers
- downloaders
- media management
